// Produktdaten, übernommen aus dem Ricardo-Shop Bmw0107 (Stand: 28.09.2026). Preise in CHF.
window.PRODUKTE = [
 {
  "id": "1200040670",
  "titel": "Elysee Automatic Moonphase",
  "marke": "Elysee",
  "kategorie": "Herren",
  "werk": "Automatik",
  "typ": "Mondphase",
  "steine": null,
  "swissMade": false,
  "limited": false,
  "preis": 399.0,
  "startpreis": 299.0,
  "preisvorschlag": false,
  "auktion": false,
  "bild": "bilder/1200040670.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/elysee-automatic-moonphase-%E2%80%94-die-uhr-fuer-den-echten-mann-1200040670/"
 },
 {
  "id": "1228649762",
  "titel": "Ingersoll Automatik Limited Edition 20 Steine",
  "marke": "Ingersoll",
  "kategorie": "Herren",
  "werk": "Automatik",
  "typ": null,
  "steine": 20,
  "swissMade": false,
  "limited": true,
  "preis": 399.0,
  "startpreis": 299.0,
  "preisvorschlag": false,
  "auktion": false,
  "bild": "bilder/1228649762.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/ingersoll-automatik-limited-edition-20-steine-1228649762/"
 },
 {
  "id": "1220401864",
  "titel": "Ingersoll Automatik Limited Edition 20 Steine",
  "marke": "Ingersoll",
  "kategorie": "Herren",
  "werk": "Automatik",
  "typ": null,
  "steine": 20,
  "swissMade": false,
  "limited": true,
  "preis": 390.0,
  "startpreis": 299.0,
  "preisvorschlag": false,
  "auktion": false,
  "bild": "bilder/1220401864.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/ingersoll-automatik-limited-edition-20-steine-1220401864/"
 },
 {
  "id": "1228763774",
  "titel": "Ingersoll Automatik Limited Edition 22 Steine",
  "marke": "Ingersoll",
  "kategorie": "Herren",
  "werk": "Automatik",
  "typ": null,
  "steine": 22,
  "swissMade": false,
  "limited": true,
  "preis": 390.0,
  "startpreis": 299.0,
  "preisvorschlag": false,
  "auktion": false,
  "bild": "bilder/1228763774.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/ingersoll-automatik-limited-edition-22-steine-1228763774/"
 },
 {
  "id": "1225726494",
  "titel": "Ingersoll Herrenuhr Limited Automatik 35 Steine",
  "marke": "Ingersoll",
  "kategorie": "Herren",
  "werk": "Automatik",
  "typ": null,
  "steine": 35,
  "swissMade": false,
  "limited": true,
  "preis": 390.0,
  "startpreis": 299.0,
  "preisvorschlag": false,
  "auktion": false,
  "bild": "bilder/1225726494.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/ingersoll-herrenuhr-limited-automatik-35-steine-1225726494/"
 },
 {
  "id": "1219836968",
  "titel": "Ingersoll Limited Edition Automatic",
  "marke": "Ingersoll",
  "kategorie": "Herren",
  "werk": "Automatik",
  "typ": null,
  "steine": null,
  "swissMade": false,
  "limited": true,
  "preis": 390.0,
  "startpreis": 299.0,
  "preisvorschlag": false,
  "auktion": false,
  "bild": "bilder/1219836968.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/ingersoll-limited-edition-automatic-1219836968/"
 },
 {
  "id": "1206879486",
  "titel": "Ingersoll Limited Edition Automatik 22 Steine",
  "marke": "Ingersoll",
  "kategorie": "Herren",
  "werk": "Automatik",
  "typ": null,
  "steine": 22,
  "swissMade": false,
  "limited": true,
  "preis": 390.0,
  "startpreis": 299.0,
  "preisvorschlag": false,
  "auktion": false,
  "bild": "bilder/1206879486.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/ingersoll-limited-edition-automatik-22-steine-1206879486/"
 },
 {
  "id": "1204866648",
  "titel": "TW Steel CB96 Canteen Bracelet Automatik Herrenuhr 50 mm, neu",
  "marke": "TW Steel",
  "kategorie": "Herren",
  "werk": "Automatik",
  "typ": null,
  "steine": null,
  "swissMade": false,
  "limited": false,
  "preis": 390.0,
  "startpreis": 299.0,
  "preisvorschlag": false,
  "auktion": false,
  "bild": "bilder/1204866648.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/tw-steel-cb96-canteen-bracelet-automatik-herrenuhr-50mm-neu-1204866648/"
 },
 {
  "id": "1233091362",
  "titel": "Ingersoll Uhr für Herren",
  "marke": "Ingersoll",
  "kategorie": "Herren",
  "werk": null,
  "typ": null,
  "steine": null,
  "swissMade": false,
  "limited": false,
  "preis": 350.0,
  "startpreis": 290.0,
  "preisvorschlag": false,
  "auktion": false,
  "bild": "bilder/1233091362.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/ingersoll-uhr-fuer-herren-1233091362/"
 },
 {
  "id": "1199908200",
  "titel": "Apogäum Automatikuhr für Herren",
  "marke": "Apogäum",
  "kategorie": "Herren",
  "werk": "Automatik",
  "typ": null,
  "steine": null,
  "swissMade": false,
  "limited": false,
  "preis": 300.0,
  "startpreis": 190.0,
  "preisvorschlag": false,
  "auktion": false,
  "bild": "bilder/1199908200.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/apogaeum-automatikuhr-fuer-herren-1199908200/"
 },
 {
  "id": "1219575336",
  "titel": "Ingersoll Automatik Limited Edition 20 Steine",
  "marke": "Ingersoll",
  "kategorie": "Herren",
  "werk": "Automatik",
  "typ": null,
  "steine": 20,
  "swissMade": false,
  "limited": true,
  "preis": 290.0,
  "startpreis": 190.0,
  "preisvorschlag": false,
  "auktion": false,
  "bild": "bilder/1219575336.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/ingersoll-automatik-limited-edition-20-steine-1219575336/"
 },
 {
  "id": "1320457816",
  "titel": "Ingersoll Herren Uhr – Wie Neu – Mit Originalbox",
  "marke": "Ingersoll",
  "kategorie": "Herren",
  "werk": null,
  "typ": null,
  "steine": null,
  "swissMade": false,
  "limited": false,
  "preis": 199.0,
  "startpreis": null,
  "preisvorschlag": false,
  "auktion": true,
  "bild": "bilder/1320457816.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/ingersoll-herren-uhr-%E2%80%93-wie-neu-%E2%80%93-mit-originalbox-1320457816/"
 },
 {
  "id": "1194037580",
  "titel": "Fossil Herren-Uhr Chronograph",
  "marke": "Fossil",
  "kategorie": "Herren",
  "werk": null,
  "typ": "Chronograph",
  "steine": null,
  "swissMade": false,
  "limited": false,
  "preis": 179.0,
  "startpreis": 99.0,
  "preisvorschlag": false,
  "auktion": false,
  "bild": "bilder/1194037580.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/fossil-herren-uhr-chronograph-1194037580/"
 },
 {
  "id": "1199058880",
  "titel": "Fossil XXLTwist-Uhr Automatik und Quartz",
  "marke": "Fossil",
  "kategorie": "Herren",
  "werk": "Automatik & Quarz",
  "typ": null,
  "steine": null,
  "swissMade": false,
  "limited": false,
  "preis": 139.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1199058880.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/fossil-xxltwist-uhr-automatik-und-quartz-1199058880/"
 },
 {
  "id": "1215811716",
  "titel": "Schweizer Uhr mit Fr. 1.- 4 Steine V8 902 101 Swiss Made",
  "marke": "Swiss Made",
  "kategorie": "Unisex",
  "werk": null,
  "typ": null,
  "steine": 4,
  "swissMade": true,
  "limited": false,
  "preis": 100.0,
  "startpreis": 79.0,
  "preisvorschlag": false,
  "auktion": false,
  "bild": "bilder/1215811716.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/schweizer-uhr-mit-fr-1-4-steine-v8-902-101-swiss-made-1215811716/"
 },
 {
  "id": "1211409114",
  "titel": "Tradition Schweizeruhr Besticktes Lederarmband Swiss Made",
  "marke": "Swiss Made",
  "kategorie": "Unisex",
  "werk": null,
  "typ": null,
  "steine": null,
  "swissMade": true,
  "limited": false,
  "preis": 100.0,
  "startpreis": 69.0,
  "preisvorschlag": false,
  "auktion": false,
  "bild": "bilder/1211409114.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/tradition-schweizeruhr-besticktes-lederarmband-swiss-made-1211409114/"
 },
 {
  "id": "1216360204",
  "titel": "Condor Uhr Automatik 17 Jewels Swiss Made",
  "marke": "Condor",
  "kategorie": "Herren",
  "werk": "Automatik",
  "typ": null,
  "steine": 17,
  "swissMade": true,
  "limited": false,
  "preis": 89.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1216360204.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/condor-uhr-automatik-17-jewels-swiss-made-1216360204/"
 },
 {
  "id": "1211384470",
  "titel": "Emporio Armani AR-0203 Original Damenuhr",
  "marke": "Emporio Armani",
  "kategorie": "Damen",
  "werk": null,
  "typ": null,
  "steine": null,
  "swissMade": false,
  "limited": false,
  "preis": 79.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1211384470.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/emporio-armani-ar-0203-original-damen-1211384470/"
 },
 {
  "id": "1212653984",
  "titel": "Swiss Made Silvana Incabloc 17 Stein Damen Armbanduhr",
  "marke": "Silvana",
  "kategorie": "Damen",
  "werk": null,
  "typ": null,
  "steine": 17,
  "swissMade": true,
  "limited": false,
  "preis": 79.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1212653984.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/swiss-made-silvana-incabloc-17-stein-damen-armbanduhr-1212653984/"
 },
 {
  "id": "1214603590",
  "titel": "Urech 21 Jewels Damenuhr Swiss Made",
  "marke": "Urech",
  "kategorie": "Damen",
  "werk": null,
  "typ": null,
  "steine": 21,
  "swissMade": true,
  "limited": false,
  "preis": 79.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1214603590.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/urech-21-jewels-damenuhr-swiss-made-1214603590/"
 },
 {
  "id": "1214585424",
  "titel": "Nivada Damenuhr 17 Stein Swiss Made",
  "marke": "Nivada",
  "kategorie": "Damen",
  "werk": null,
  "typ": null,
  "steine": 17,
  "swissMade": true,
  "limited": false,
  "preis": 78.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1214585424.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/nivada-damenuhr-17-stein-swiss-made-1214585424/"
 },
 {
  "id": "1211850080",
  "titel": "LG Langemann Germany Herren-Uhr",
  "marke": "LG Langemann",
  "kategorie": "Herren",
  "werk": null,
  "typ": null,
  "steine": null,
  "swissMade": false,
  "limited": false,
  "preis": 69.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1211850080.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/lg-langemann-germany-herren-uhr-1211850080/"
 },
 {
  "id": "1214701390",
  "titel": "Rotary Schockresistant Waterresistant 17 Jewels Swiss Made",
  "marke": "Rotary",
  "kategorie": "Herren",
  "werk": null,
  "typ": null,
  "steine": 17,
  "swissMade": true,
  "limited": false,
  "preis": 69.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1214701390.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/rotary-schockresistant-waterresistant-17-jewels-swiss-made-1214701390/"
 },
 {
  "id": "1082930386",
  "titel": "Swatch Chronograph Swiss Made Sportlich",
  "marke": "Swatch",
  "kategorie": "Unisex",
  "werk": "Quarz",
  "typ": "Chronograph",
  "steine": null,
  "swissMade": true,
  "limited": false,
  "preis": 69.0,
  "startpreis": null,
  "preisvorschlag": false,
  "auktion": false,
  "bild": null,
  "ricardo": "https://www.ricardo.ch/de/a/swatch-chronograph-swiss-made-sportliche-1082930386/"
 },
 {
  "id": "1092472672",
  "titel": "Swatch Swiss Made V8",
  "marke": "Swatch",
  "kategorie": "Unisex",
  "werk": "Quarz",
  "typ": null,
  "steine": null,
  "swissMade": true,
  "limited": false,
  "preis": 69.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1092472672.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/swatch-swiss-made-v8-1092472672/"
 },
 {
  "id": "1211682706",
  "titel": "Swiss Ermano Damen-Uhr Automatik 21 Steine",
  "marke": "Swiss Ermano",
  "kategorie": "Damen",
  "werk": "Automatik",
  "typ": null,
  "steine": 21,
  "swissMade": true,
  "limited": false,
  "preis": 69.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1211682706.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/swiss-ermano-damen-uhr-automatik-21-steine-1211682706/"
 },
 {
  "id": "1214617464",
  "titel": "Delma of Switzerland Damenuhr",
  "marke": "Delma",
  "kategorie": "Damen",
  "werk": null,
  "typ": null,
  "steine": null,
  "swissMade": true,
  "limited": false,
  "preis": 59.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1214617464.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/delma-of-switzerland-damenuhr-1214617464/"
 },
 {
  "id": "1077553118",
  "titel": "Michael Delaby Damenuhr",
  "marke": "Michael Delaby",
  "kategorie": "Damen",
  "werk": null,
  "typ": null,
  "steine": null,
  "swissMade": false,
  "limited": false,
  "preis": 59.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1077553118.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/michael-delaby-damenuhr-1077553118/"
 },
 {
  "id": "1195025146",
  "titel": "Swatch Original Swiss Made",
  "marke": "Swatch",
  "kategorie": "Unisex",
  "werk": "Quarz",
  "typ": null,
  "steine": null,
  "swissMade": true,
  "limited": false,
  "preis": 59.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1195025146.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/swatch-original-swiss-made-1195025146/"
 },
 {
  "id": "1201224062",
  "titel": "Swatch Uhr Swiss Made",
  "marke": "Swatch",
  "kategorie": "Unisex",
  "werk": "Quarz",
  "typ": null,
  "steine": null,
  "swissMade": true,
  "limited": false,
  "preis": 59.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1201224062.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/swatch-uhr-swiss-made-1201224062/"
 },
 {
  "id": "1201225126",
  "titel": "Swatch-Uhr Swiss Made",
  "marke": "Swatch",
  "kategorie": "Unisex",
  "werk": "Quarz",
  "typ": null,
  "steine": null,
  "swissMade": true,
  "limited": false,
  "preis": 59.0,
  "startpreis": null,
  "preisvorschlag": true,
  "auktion": false,
  "bild": "bilder/1201225126.jpg",
  "ricardo": "https://www.ricardo.ch/de/a/swatch-uhr-swiss-made-1201225126/"
 }
];
